[package]
name = "glyph-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
glyph-core = { path = "../glyph-core" }
glyph-scene = { path = "../glyph-scene" }
glyph-path = { path = "../glyph-path" }
glyph-paint = { path = "../glyph-paint" }
glyph-text = { path = "../glyph-text" }
serde = { workspace = true }
