[package]
name = "glyph-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "glyph"
path = "src/main.rs"

[dependencies]
glyph-core = { path = "../glyph-core" }
glyph-scene = { path = "../glyph-scene" }
glyph-render = { path = "../glyph-render" }
glyph-path = { path = "../glyph-path" }
glyph-paint = { path = "../glyph-paint" }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
